<option value="Afganistan">Афганистан</option>
<option value="Albania">Албания</option>
<option value="Algeria">Алжир</option>
<option value="American Samoa">Американское Самоа</option>
<option value="Andorra">Андорра</option>
<option value="Angola">Ангола</option>
<option value="Anguilla">Ангилья</option>
<option value="Antigua & Barbuda">Антигуа и Барбуда</option>
<option value="Argentina">Аргентина</option>
<option value="Armenia">Армения</option>
<option value="Aruba">Аруба</option>
<option value="Australia">Австралия</option>
<option value="Austria">Австрия</option>
<option value="Azerbaijan">Азербайджан</option>
<option value="Bahamas">Багамские Острова</option>
<option value="Bahrain">Бахрейн</option>
<option value="Bangladesh">Бангладеш</option>
<option value="Barbados">Барбадос</option>
<option value="Belarus">Беларусь</option>
<option value="Belgium">Бельгия</option>
<option value="Belize">Белиз</option>
<option value="Benin">Бенин</option>
<option value="Bermuda">Бермудские Острова</option>
<option value="Bhutan">Бутан</option>
<option value="Bolivia">Боливия</option>
<option value="Bonaire">Бонайре</option>
<option value="Bosnia & Herzegovina">Босния и Герцеговина</option>
<option value="Botswana">Ботсвана</option>
<option value="Brazil">Бразилия</option>
<option value="British Indian Ocean Ter">Британская территория в Индийском океане</option>
<option value="Brunei">Бруней</option>
<option value="Bulgaria">Болгария</option>
<option value="Burkina Faso">Буркина-Фасо</option>
<option value="Burundi">Бурунди</option>
<option value="Cambodia">Камбоджа</option>
<option value="Cameroon">Камерун</option>
<option value="Canada">Канада</option>
<option value="Canary Islands">Канарские острова</option>
<option value="Cape Verde">Кабо-Верде</option>
<option value="Cayman Islands">Каймановы острова</option>
<option value="Central African Republic">Центральноафриканская Республика</option>
<option value="Chad">Чад</option>
<option value="Channel Islands">Нормандские острова</option>
<option value="Chile">Чили</option>
<option value="China">Китай</option>
<option value="Christmas Island">Остров Рождества</option>
<option value="Cocos Island">Кокосовые острова</option>
<option value="Colombia">Колумбия</option>
<option value="Comoros">Коморы</option>
<option value="Congo">Конго</option>
<option value="Cook Islands">Острова Кука</option>
<option value="Costa Rica">Коста-Рика</option>
<option value="Cote DIvoire">Кот-д'Ивуар</option>
<option value="Croatia">Хорватия</option>
<option value="Cuba">Куба</option>
<option value="Curaco">Кюрасао</option>
<option value="Cyprus">Кипр</option>
<option value="Czech Republic">Чехия</option>
<option value="Denmark">Дания</option>
<option value="Djibouti">Джибути</option>
<option value="Dominica">Доминика</option>
<option value="Dominican Republic">Доминиканская Республика</option>
<option value="East Timor">Восточный Тимор</option>
<option value="Ecuador">Эквадор</option>
<option value="Egypt">Египет</option>
<option value="El Salvador">Сальвадор</option>
<option value="Equatorial Guinea">Экваториальная Гвинея</option>
<option value="Eritrea">Эритрея</option>
<option value="Estonia">Эстония</option>
<option value="Ethiopia">Эфиопия</option>
<option value="Falkland Islands">Фолклендские острова</option>
<option value="Faroe Islands">Фарерские острова</option>
<option value="Fiji">Фиджи</option>
<option value="Finland">Финляндия</option>
<option value="France">Франция</option>
<option value="French Guiana">Французская Гвиана</option>
<option value="French Polynesia">Французская Полинезия</option>
<option value="French Southern Ter">Французские Южные территории</option>
<option value="Gabon">Габон</option>
<option value="Gambia">Гамбия</option>
<option value="Georgia">Грузия</option>
<option value="Germany">Германия</option>
<option value="Ghana">Гана</option>
<option value="Gibraltar">Гибралтар</option>
<option value="Great Britain">Великобритания</option>
<option value="Greece">Греция</option>
<option value="Greenland">Гренландия</option>
<option value="Grenada">Гренада</option>
<option value="Guadeloupe">Гваделупа</option>
<option value="Guam">Гуам</option>
<option value="Guatemala">Гватемала</option>
<option value="Guinea">Гвинея</option>
<option value="Guyana">Гайана</option>
<option value="Haiti">Гаити</option>
<option value="Hawaii">Гавайи</option>
<option value="Honduras">Гондурас</option>
<option value="Hong Kong">Гонконг</option>
<option value="Hungary">Венгрия</option>
<option value="Iceland">Исландия</option>
<option value="India">Индия</option>
<option value="Indonesia">Индонезия</option>
<option value="Iran">Иран</option>
<option value="Iraq">Ирак</option>
<option value="Ireland">Ирландия</option>
<option value="Isle of Man">Остров Мэн</option>
<option value="Israel">Израиль</option>
<option value="Italy">Италия</option>
<option value="Jamaica">Ямайка</option>
<option value="Japan">Япония</option>
<option value="Jordan">Иордания</option>
<option value="Kazakhstan">Казахстан</option>
<option value="Kenya">Кения</option>
<option value="Kiribati">Кирибати</option>
<option value="Korea North">Северная Корея</option>
<option value="Korea Sout">Южная Корея</option>
<option value="Kuwait">Кувейт</option>
<option value="Kyrgyzstan">Кыргызстан</option>
<option value="Laos">Лаос</option>
<option value="Latvia">Латвия</option>
<option value="Lebanon">Ливан</option>
<option value="Lesotho">Лесото</option>
<option value="Liberia">Либерия</option>
<option value="Libya">Ливия</option>
<option value="Liechtenstein">Лихтенштейн</option>
<option value="Lithuania">Литва</option>
<option value="Luxembourg">Люксембург</option>
<option value="Macau">Макао</option>
<option value="Macedonia">Македония</option>
<option value="Madagascar">Мадагаскар</option>
<option value="Malaysia">Малайзия</option>
<option value="Malawi">Малави</option>
<option value="Maldives">Мальдивы</option>
<option value="Mali">Мали</option>
<option value="Malta">Мальта</option>
<option value="Marshall Islands">Маршалловы острова</option>
<option value="Martinique">Мартиника</option>
<option value="Mauritania">Мавритания</option>
<option value="Mauritius">Маврикий</option>
<option value="Mayotte">Майотта</option>
<option value="Mexico">Мексика</option>
<option value="Midway Islands">Острова Мидуэй</option>
<option value="Moldova">Молдова</option>
<option value="Monaco">Монако</option>
<option value="Mongolia">Монголия</option>
<option value="Montserrat">Монтсеррат</option>
<option value="Morocco">Марокко</option>
<option value="Mozambique">Мозамбик</option>
<option value="Myanmar">Мьянма</option>
<option value="Nambia">Намибия</option>
<option value="Nauru">Науру</option>
<option value="Nepal">Непал</option>
<option value="Netherland Antilles">Нидерландские Антильские острова</option>
<option value="Netherlands">Нидерланды (Европа)</option>
<option value="Nevis">Невис</option>
<option value="New Caledonia">Новая Каледония</option>
<option value="New Zealand">Новая Зеландия</option>
<option value="Nicaragua">Никарагуа</option>
<option value="Niger">Нигер</option>
<option value="Nigeria">Нигерия</option>
<option value="Niue">Ниуэ</option>
<option value="Norfolk Island">Остров Норфолк</option>
<option value="Norway">Норвегия</option>
<option value="Oman">Оман</option>
<option value="Pakistan">Пакистан</option>
<option value="Palau Island">Палау</option>
<option value="Palestine">Палестина</option>
<option value="Panama">Панама</option>
<option value="Papua New Guinea">Папуа — Новая Гвинея</option>
<option value="Paraguay">Парагвай</option>
<option value="Peru">Перу</option>
<option value="Phillipines">Филиппины</option>
<option value="Pitcairn Island">Острова Питкэрн</option>
<option value="Poland">Польша</option>
<option value="Portugal">Португалия</option>
<option value="Puerto Rico">Пуэрто-Рико</option>
<option value="Qatar">Катар</option>
<option value="Republic of Montenegro">Черногория</option>
<option value="Republic of Serbia">Сербия</option>
<option value="Reunion">Реюньон</option>
<option value="Romania">Румыния</option>
<option value="Russia">Россия</option>
<option value="Rwanda">Руанда</option>
<option value="St Barthelemy">Сен-Бартелеми</option>
<option value="St Eustatius">Сен-Эстатиус</option>
<option value="St Helena">Святая Елена</option>
<option value="St Kitts-Nevis">Сент-Китс и Невис</option>
<option value="St Lucia">Сент-Люсия</option>
<option value="St Maarten">Сен-Мартен</option>
<option value="St Pierre & Miquelon">Сен-Пьер и Микелон</option>
<option value="St Vincent & Grenadines">Сент-Винсент и Гренадины</option>
<option value="Saipan">Сайпан</option>
<option value="Samoa">Самоа</option>
<option value="Samoa American">Американское Самоа</option>
<option value="San Marino">Сан-Марино</option>
<option value="Sao Tome & Principe">Сан-Томе и Принсипи</option>
<option value="Saudi Arabia">Саудовская Аравия</option>
<option value="Senegal">Сенегал</option>
<option value="Serbia">Сербия</option>
<option value="Seychelles">Сейшельские острова</option>
<option value="Sierra Leone">Сьерра-Леоне</option>
<option value="Singapore">Сингапур</option>
<option value="Slovakia">Словакия</option>
<option value="Slovenia">Словения</option>
<option value="Solomon Islands">Соломоновы острова</option>
<option value="Somalia">Сомали</option>
<option value="South Africa">ЮАР</option>
<option value="Spain">Испания</option>
<option value="Sri Lanka">Шри-Ланка</option>
<option value="Sudan">Судан</option>
<option value="Suriname">Суринам</option>
<option value="Swaziland">Эсватини</option>
<option value="Sweden">Швеция</option>
<option value="Switzerland">Швейцария</option>
<option value="Syria">Сирия</option>
<option value="Tahiti">Таити</option>
<option value="Taiwan">Тайвань</option>
<option value="Tajikistan">Таджикистан</option>
<option value="Tanzania">Танзания</option>
<option value="Thailand">Таиланд</option>
<option value="Togo">Того</option>
<option value="Tokelau">Токелау</option>
<option value="Tonga">Тонга</option>
<option value="Trinidad & Tobago">Тринидад и Тобаго</option>
<option value="Tunisia">Тунис</option>
<option value="Turkey">Турция</option>
<option value="Turkmenistan">Туркменистан</option>
<option value="Turks & Caicos Is">Острова Теркс и Кайкос</option>
<option value="Tuvalu">Тувалу</option>
<option value="Uganda">Уганда</option>
<option value="Ukraine">Украина</option>
<option value="United Arab Erimates">Объединенные Арабские Эмираты</option>
<option value="United Kingdom">Великобритания</option>
<option value="United States of America">Соединенные Штаты Америки</option>
<option value="Uraguay">Уругвай</option>
<option value="Uzbekistan">Узбекистан</option>
<option value="Vanuatu">Вануату</option>
<option value="Vatican City State">Государство-город Ватикан</option>
<option value="Venezuela">Венесуэла</option>
<option value="Vietnam">Вьетнам</option>
<option value="Virgin Islands (Brit)">Британские Виргинские острова</option>
<option value="Virgin Islands (USA)">Виргинские острова США</option>
<option value="Wake Island">Остров Уэйк</option>
<option value="Wallis & Futana Is">Уоллис и Футуна</option>
<option value="Yemen">Йемен</option>
<option value="Zaire">Заир</option>
<option value="Zambia">Замбия</option>
<option value="Zimbabwe">Зимбабве</option>