<option value="Afganistan">Afganistan</option>
<option value="Albania">Arnavutluk</option>
<option value="Algeria">Cezayir</option>
<option value="American Samoa">Amerikan Samoası</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antigua & Barbuda">Antigua ve Barbuda</option>
<option value="Argentina">Arjantin</option>
<option value="Armenia">Ermenistan</option>
<option value="Aruba">Aruba</option>
<option value="Australia">Avustralya</option>
<option value="Austria">Avusturya</option>
<option value="Azerbaijan">Azerbaycan</option>
<option value="Bahamas">Bahamalar</option>
<option value="Bahrain">Bahreyn</option>
<option value="Bangladesh">Bangladeş</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belçika</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivya</option>
<option value="Bonaire">Bonaire</option>
<option value="Bosnia & Herzegovina">Bosna-Hersek</option>
<option value="Botswana">Botsvana</option>
<option value="Brazil">Brezilya</option>
<option value="British Indian Ocean Ter">Britanya Hint Okyanusu Toprakları</option>
<option value="Brunei">Brunei</option>
<option value="Bulgaria">Bulgaristan</option>
<option value="Burkina Faso">Burkina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Kamboçya</option>
<option value="Cameroon">Kamerun</option>
<option value="Canada">Kanada</option>
<option value="Canary Islands">Kanarya Adaları</option>
<option value="Cape Verde">Yeşil Burun Adaları</option>
<option value="Cayman Islands">Cayman Adaları</option>
<option value="Central African Republic">Orta Afrika Cumhuriyeti</option>
<option value="Chad">Çad</option>
<option value="Channel Islands">Kanal Adaları</option>
<option value="Chile">Şili</option>
<option value="China">Çin</option>
<option value="Christmas Island">Noel Adası</option>
<option value="Cocos Island">Cocos Adası</option>
<option value="Colombia">Kolombiya</option>
<option value="Comoros">Komorlar</option>
<option value="Congo">Kongo</option>
<option value="Cook Islands">Cook Adaları</option>
<option value="Costa Rica">Kosta Rika</option>
<option value="Cote DIvoire">Fildişi Sahili</option>
<option value="Croatia">Hırvatistan</option>
<option value="Cuba">Küba</option>
<option value="Curaco">Curaçao</option>
<option value="Cyprus">Kıbrıs</option>
<option value="Czech Republic">Çek Cumhuriyeti</option>
<option value="Denmark">Danimarka</option>
<option value="Djibouti">Cibuti</option>
<option value="Dominica">Dominika</option>
<option value="Dominican Republic">Dominik Cumhuriyeti</option>
<option value="East Timor">Doğu Timor</option>
<option value="Ecuador">Ekvador</option>
<option value="Egypt">Mısır</option>
<option value="El Salvador">El Salvador</option>
<option value="Equatorial Guinea">Ekvator Ginesi</option>
<option value="Eritrea">Eritre</option>
<option value="Estonia">Estonya</option>
<option value="Ethiopia">Etiyopya</option>
<option value="Falkland Islands">Falkland Adaları</option>
<option value="Faroe Islands">Faroe Adaları</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finlandiya</option>
<option value="France">Fransa</option>
<option value="French Guiana">Fransız Guyanası</option>
<option value="French Polynesia">Fransız Polinezyası</option>
<option value="French Southern Ter">Fransız Güney Toprakları</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambiya</option>
<option value="Georgia">Gürcistan</option>
<option value="Germany">Almanya</option>
<option value="Ghana">Gana</option>
<option value="Gibraltar">Cebelitarık</option>
<option value="Great Britain">Büyük Britanya</option>
<option value="Greece">Yunanistan</option>
<option value="Greenland">Grönland</option>
<option value="Grenada">Grenada</option>
<option value="Guadeloupe">Guadeloupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guinea">Gine</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Hawaii">Hawaii</option>
<option value="Honduras">Honduras</option>
<option value="Hong Kong">Hong Kong</option>
<option value="Hungary">Macaristan</option>
<option value="Iceland">İzlanda</option>
<option value="India">Hindistan</option>
<option value="Indonesia">Endonezya</option>
<option value="Iran">İran</option>
<option value="Iraq">Irak</option>
<option value="Ireland">İrlanda</option>
<option value="Isle of Man">Man Adası</option>
<option value="Israel">İsrail</option>
<option value="Italy">İtalya</option>
<option value="Jamaica">Jamaika</option>
<option value="Japan">Japonya</option>
<option value="Jordan">Ürdün</option>
<option value="Kazakhstan">Kazakistan</option>
<option value="Kenya">Kenya</option>
<option value="Kiribati">Kiribati</option>
<option value="Korea North">Kuzey Kore</option>
<option value="Korea Sout">Güney Kore</option>
<option value="Kuwait">Kuveyt</option>
<option value="Kyrgyzstan">Kırgızistan</option>
<option value="Laos">Laos</option>
<option value="Latvia">Letonya</option>
<option value="Lebanon">Lübnan</option>
<option value="Lesotho">Lesotho</option>
<option value="Liberia">Liberya</option>
<option value="Libya">Libya</option>
<option value="Liechtenstein">Lihtenştayn</option>
<option value="Lithuania">Litvanya</option>
<option value="Luxembourg">Lüksemburg</option>
<option value="Macau">Macau</option>
<option value="Macedonia">Makedonya</option>
<option value="Madagascar">Madagaskar</option>
<option value="Malaysia">Malezya</option>
<option value="Malawi">Malavi</option>
<option value="Maldives">Maldivler</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marshall Islands">Marshall Adaları</option>
<option value="Martinique">Martinik</option>
<option value="Mauritania">Moritanya</option>
<option value="Mauritius">Mauritius</option>
<option value="Mayotte">Mayotte</option>
<option value="Mexico">Meksika</option>
<option value="Midway Islands">Midway Adaları</option>
<option value="Moldova">Moldova</option>
<option value="Monaco">Monako</option>
<option value="Mongolia">Moğolistan</option>
<option value="Montserrat">Montserrat</option>
<option value="Morocco">Fas</option>
<option value="Mozambique">Mozambik</option>
<option value="Myanmar">Myanmar</option>
<option value="Nambia">Namibya</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Netherland Antilles">Hollanda Antilleri</option>
<option value="Netherlands">Hollanda (Avrupa)</option>
<option value="Nevis">Nevis</option>
<option value="New Caledonia">Yeni Kaledonya</option>
<option value="New Zealand">Yeni Zelanda</option>
<option value="Nicaragua">Nikaragua</option>
<option value="Niger">Nijer</option>
<option value="Nigeria">Nijerya</option>
<option value="Niue">Niue</option>
<option value="Norfolk Island">Norfolk Adası</option>
<option value="Norway">Norveç</option>
<option value="Oman">Umman</option>
<option value="Pakistan">Pakistan</option>
<option value="Palau Island">Palau Adası</option>
<option value="Palestine">Filistin</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua Yeni Gine</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="Phillipines">Filipinler</option>
<option value="Pitcairn Island">Pitcairn Adası</option>
<option value="Poland">Polonya</option>
<option value="Portugal">Portekiz</option>
<option value="Puerto Rico">Porto Riko</option>
<option value="Qatar">Katar</option>
<option value="Republic of Montenegro">Karadağ Cumhuriyeti</option>
<option value="Republic of Serbia">Sırbistan Cumhuriyeti</option>
<option value="Reunion">Réunion</option>
<option value="Romania">Romanya</option>
<option value="Russia">Rusya</option>
<option value="Rwanda">Ruanda</option>
<option value="St Barthelemy">Saint Barthelemy</option>
<option value="St Eustatius">Saint Eustatius</option>
<option value="St Helena">Saint Helena</option>
<option value="St Kitts-Nevis">Saint Kitts ve Nevis</option>
<option value="St Lucia">Saint Lucia</option>
<option value="St Maarten">Saint Maarten</option>
<option value="St Pierre & Miquelon">Saint Pierre ve Miquelon</option>
<option value="St Vincent & Grenadines">Saint Vincent ve Grenadinler</option>
<option value="Saipan">Saipan</option>
<option value="Samoa">Samoa</option>
<option value="Samoa American">Amerikan Samoası</option>
<option value="San Marino">San Marino</option>
<option value="Sao Tome & Principe">Sao Tome ve Principe</option>
<option value="Saudi Arabia">Suudi Arabistan</option>
<option value="Senegal">Senegal</option>
<option value="Serbia">Sırbistan</option>
<option value="Seychelles">Seyşeller</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapur</option>
<option value="Slovakia">Slovakya</option>
<option value="Slovenia">Slovenya</option>
<option value="Solomon Islands">Solomon Adaları</option>
<option value="Somalia">Somali</option>
<option value="South Africa">Güney Afrika</option>
<option value="Spain">İspanya</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Sudan</option>
<option value="Suriname">Surinam</option>
<option value="Swaziland">Svaziland</option>
<option value="Sweden">İsveç</option>
<option value="Switzerland">İsviçre</option>
<option value="Syria">Suriye</option>
<option value="Tahiti">Tahiti</option>
<option value="Taiwan">Tayvan</option>
<option value="Tajikistan">Tacikistan</option>
<option value="Tanzania">Tanzanya</option>
<option value="Thailand">Tayland</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad & Tobago">Trinidad ve Tobago</option>
<option value="Tunisia">Tunus</option>
<option value="Turkey">Türkiye</option>
<option value="Turkmenistan">Türkmenistan</option>
<option value="Turks & Caicos Is">Turks ve Caicos Adaları</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="Ukraine">Ukrayna</option>
<option value="United Arab Erimates">Birleşik Arap Emirlikleri</option>
<option value="United Kingdom">Birleşik Krallık</option>
<option value="United States of America">Amerika Birleşik Devletleri</option>
<option value="Uraguay">Uruguay</option>
<option value="Uzbekistan">Özbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Vatican City State">Vatikan Şehir Devleti</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietnam">Vietnam</option>
<option value="Virgin Islands (Brit)">Britanya Virjin Adaları</option>
<option value="Virgin Islands (USA)">ABD Virjin Adaları</option>
<option value="Wake Island">Wake Adası</option>
<option value="Wallis & Futana Is">Wallis ve Futuna Adaları</option>
<option value="Yemen">Yemen</option>
<option value="Zaire">Zaire</option>
<option value="Zambia">Zambiya</option>
<option value="Zimbabwe">Zimbabve</option>