services:
  # PHP-FPM Service
  app-vicsafe:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql-vicsafe

  # Nginx Service
  nginx-vicsafe:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-vicsafe

  # MySQL Service
  mysql-vicsafe:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vicsafe
      MYSQL_ROOT_PASSWORD: si6echoYuc98asti
      MYSQL_USER: user
      MYSQL_PASSWORD: sPl2ltlt1emaV5t9
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data_vicsafe:/var/lib/mysql

  # Redis Service (optional but useful for Laravel)
  redis-vicsafe:
    image: redis:alpine
    restart: unless-stopped

  # PhpMyAdmin Service (optional for database management)
  phpmyadmin-vicsafe:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-vicsafe
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      APACHE_HTTP_PORT_NUMBER: 80
      APACHE_HTTPS_PORT_NUMBER: 443
      PMA_CONTROLUSER: user
      PMA_CONTROLPASS: sPl2ltlt1emaV5t9
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    depends_on:
      - mysql-vicsafe

# Docker Networks
networks:
  default:
    external: true
    name: proxy-network

# Volumes
volumes:
  mysql_data_vicsafe:
    driver: local