name: Deploy Laravel via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to HestiaCP server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/monexa
            docker-compose down --remove-orphans
            git pull origin main
            docker-compose up -d --remove-orphans
            docker-compose exec app composer install --no-interaction --no-dev --optimize-autoloader
            docker-compose exec app php artisan optimize
